name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 5 * * *'

env:
  DNSSERVER: "aliyun"  # aliyun or dnspod
  UPDATE_IPV4: true
  UPDATE_IPV6: true
  KEY: ${{ secrets.KEY }}
  DOMAIN_INFO: ${{ secrets.DOMAIN_INFO }}
  SECRET_ID: ${{ secrets.SECRETID }}
  SECRET_KEY: ${{ secrets.SECRETKEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run cf2dns v4'
        if: env.UPDATE_IPV4 == 'true' && !cancelled()
        run: python cf2dns.py ${DNSSERVER} -4
      - name: 'run cf2dns v6'
        if: env.UPDATE_IPV4 == 'true' && !cancelled()
        run: python cf2dns.py ${DNSSERVER} -6
